repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: semgrep
        name: semgrep
        entry: semgrep scan --config security-rules/semgrep-local.yaml --error
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/bridgecrewio/checkov
    rev: '3.2.508'
    hooks:
      - id: checkov
        args: ['-d', '.', '--skip-path', 'venv']
        pass_filenames: false
        always_run: true
